### ISSUE TITLE
Dropped items lost their prefix.

### ISSUE THREAD

**Issue by tanpro260196** [sgkoishi/CustomDifficulty#3]
Items like Accessory and Weapon lost their prefix when drop from player's inventory upon death.
Probably the plugin forgot to include item's prefix when spawn item at player's death location?

**Comment by tanpro260196** [comment]
Can you fix this pls?

**Comment by sgkoishi** [comment]
Fixed 5f51e968c1733a8f4492745d2e7012e61aff8c0d
